angular.module('myApp',['ui.router'])
  .config(function($stateProvider,$urlRouterProvider){
     $urlRouterProvider.when("","/page-tab") ;
     $stateProvider
       .state("page-tab",{
           url:"/page-tab",
           templateUrl:"/page-tab.html"
       })
       .state("page-tab.page1",{
           url:"/page1",
           templateUrl:"/page-tab/page1.html"
       })
       .state("page-tab.page2",{
           url:"/page2",
           templateUrl:"/page-tab/page2.html"
       })
       .state("page-tab.page3",{
           url:"/page3",
           templateUrl:"/page-tab/page3.html"
       });
  });                                                                                                                                                                                                                                                                                   